// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CategoryType string

const (
	CategoryTypeElectronics   CategoryType = "electronics"
	CategoryTypeEntertainment CategoryType = "entertainment"
	CategoryTypeEducation     CategoryType = "education"
	CategoryTypeClothing      CategoryType = "clothing"
	CategoryTypeWork          CategoryType = "work"
	CategoryTypeSports        CategoryType = "sports"
)

func (e *CategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoryType(s)
	case string:
		*e = CategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoryType: %T", src)
	}
	return nil
}

type NullCategoryType struct {
	CategoryType CategoryType `json:"category_type"`
	Valid        bool         `json:"valid"` // Valid is true if CategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.CategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoryType), nil
}

type FrequencyType string

const (
	FrequencyTypeDaily   FrequencyType = "daily"
	FrequencyTypeWeekly  FrequencyType = "weekly"
	FrequencyTypeMonthly FrequencyType = "monthly"
	FrequencyTypeYearly  FrequencyType = "yearly"
)

func (e *FrequencyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrequencyType(s)
	case string:
		*e = FrequencyType(s)
	default:
		return fmt.Errorf("unsupported scan type for FrequencyType: %T", src)
	}
	return nil
}

type NullFrequencyType struct {
	FrequencyType FrequencyType `json:"frequency_type"`
	Valid         bool          `json:"valid"` // Valid is true if FrequencyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrequencyType) Scan(value interface{}) error {
	if value == nil {
		ns.FrequencyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrequencyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrequencyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrequencyType), nil
}

type TokenPurpose string

const (
	TokenPurposeEmailVerification TokenPurpose = "email_verification"
	TokenPurposePasswordReset     TokenPurpose = "password_reset"
)

func (e *TokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenPurpose(s)
	case string:
		*e = TokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenPurpose: %T", src)
	}
	return nil
}

type NullTokenPurpose struct {
	TokenPurpose TokenPurpose `json:"token_purpose"`
	Valid        bool         `json:"valid"` // Valid is true if TokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.TokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenPurpose), nil
}

type TransactionType string

const (
	TransactionTypeExpense      TransactionType = "expense"
	TransactionTypeIncome       TransactionType = "income"
	TransactionTypeSubscription TransactionType = "subscription"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Payment struct {
	ID         int32             `json:"id"`
	UserID     int32             `json:"user_id"`
	Name       string            `json:"name"`
	Amount     pgtype.Numeric    `json:"amount"`
	Type       TransactionType   `json:"type"`
	Category   CategoryType      `json:"category"`
	Date       string            `json:"date"`
	DueDate    pgtype.Text       `json:"due_date"`
	Paid       bool              `json:"paid"`
	PaidAt     pgtype.Text       `json:"paid_at"`
	Recurrent  bool              `json:"recurrent"`
	Frequency  NullFrequencyType `json:"frequency"`
	ReceiptUrl pgtype.Text       `json:"receipt_url"`
}

type User struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	Role         UserRole           `json:"role"`
	GoogleID     pgtype.Text        `json:"google_id"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserToken struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Purpose   TokenPurpose       `json:"purpose"`
	Used      bool               `json:"used"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
