// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CategoryType string

const (
	CategoryTypeElectronics   CategoryType = "electronics"
	CategoryTypeEntertainment CategoryType = "entertainment"
	CategoryTypeEducation     CategoryType = "education"
	CategoryTypeClothing      CategoryType = "clothing"
	CategoryTypeWork          CategoryType = "work"
	CategoryTypeSports        CategoryType = "sports"
)

func (e *CategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoryType(s)
	case string:
		*e = CategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoryType: %T", src)
	}
	return nil
}

type NullCategoryType struct {
	CategoryType CategoryType `json:"category_type"`
	Valid        bool         `json:"valid"` // Valid is true if CategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.CategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoryType), nil
}

type FrequencyType string

const (
	FrequencyTypeDaily   FrequencyType = "daily"
	FrequencyTypeWeekly  FrequencyType = "weekly"
	FrequencyTypeMonthly FrequencyType = "monthly"
	FrequencyTypeYearly  FrequencyType = "yearly"
)

func (e *FrequencyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrequencyType(s)
	case string:
		*e = FrequencyType(s)
	default:
		return fmt.Errorf("unsupported scan type for FrequencyType: %T", src)
	}
	return nil
}

type NullFrequencyType struct {
	FrequencyType FrequencyType `json:"frequency_type"`
	Valid         bool          `json:"valid"` // Valid is true if FrequencyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrequencyType) Scan(value interface{}) error {
	if value == nil {
		ns.FrequencyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrequencyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrequencyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrequencyType), nil
}

type TransactionType string

const (
	TransactionTypeExpense      TransactionType = "expense"
	TransactionTypeIncome       TransactionType = "income"
	TransactionTypeSubscription TransactionType = "subscription"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Payment struct {
	ID         int32             `json:"id"`
	UserID     int32             `json:"user_id"`
	Name       string            `json:"name"`
	Amount     pgtype.Numeric    `json:"amount"`
	Type       TransactionType   `json:"type"`
	Category   CategoryType      `json:"category"`
	Date       string            `json:"date"`
	DueDate    pgtype.Text       `json:"due_date"`
	Paid       bool              `json:"paid"`
	PaidAt     pgtype.Text       `json:"paid_at"`
	Recurrent  bool              `json:"recurrent"`
	Frequency  NullFrequencyType `json:"frequency"`
	ReceiptUrl pgtype.Text       `json:"receipt_url"`
}

type User struct {
	ID                    int32              `json:"id"`
	Username              string             `json:"username"`
	Email                 string             `json:"email"`
	Password              string             `json:"password"`
	Active                bool               `json:"active"`
	EmailVerificationHash pgtype.Text        `json:"email_verification_hash"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	TokenExpiresAt        pgtype.Timestamptz `json:"token_expires_at"`
}
