// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_user_tokens.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO
  user_tokens (user_id, token_hash, purpose, expires_at)
VALUES
  ($1, $2, $3, $4)
RETURNING
  id, user_id, token_hash, purpose, used, expires_at, created_at
`

type CreateUserTokenParams struct {
	UserID    int32              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Purpose   TokenPurpose       `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error) {
	row := q.db.QueryRow(ctx, createUserToken,
		arg.UserID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteByUserAndPurpose = `-- name: DeleteByUserAndPurpose :exec
DELETE FROM user_tokens
WHERE
  user_id = $1
  AND purpose = $2
`

type DeleteByUserAndPurposeParams struct {
	UserID  int32        `json:"user_id"`
	Purpose TokenPurpose `json:"purpose"`
}

func (q *Queries) DeleteByUserAndPurpose(ctx context.Context, arg DeleteByUserAndPurposeParams) error {
	_, err := q.db.Exec(ctx, deleteByUserAndPurpose, arg.UserID, arg.Purpose)
	return err
}

const deleteOldTokens = `-- name: DeleteOldTokens :execrows
DELETE FROM user_tokens
WHERE
  used = TRUE
  OR expires_at < NOW()
`

func (q *Queries) DeleteOldTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT
  id,
  user_id,
  token_hash,
  purpose,
  used,
  expires_at,
  created_at
FROM
  user_tokens
WHERE
  token_hash = $1
  AND purpose = $2
  AND used = FALSE
  AND expires_at > NOW()
LIMIT
  1
`

type GetTokenByHashParams struct {
	TokenHash string       `json:"token_hash"`
	Purpose   TokenPurpose `json:"purpose"`
}

func (q *Queries) GetTokenByHash(ctx context.Context, arg GetTokenByHashParams) (UserToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, arg.TokenHash, arg.Purpose)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const verifyAndConsumeToken = `-- name: VerifyAndConsumeToken :one
UPDATE user_tokens
SET
  used = TRUE
WHERE
  token_hash = $1
  AND purpose = $2
  AND used = false
  AND expires_at > NOW()
RETURNING
  id, user_id, token_hash, purpose, used, expires_at, created_at
`

type VerifyAndConsumeTokenParams struct {
	TokenHash string       `json:"token_hash"`
	Purpose   TokenPurpose `json:"purpose"`
}

func (q *Queries) VerifyAndConsumeToken(ctx context.Context, arg VerifyAndConsumeTokenParams) (UserToken, error) {
	row := q.db.QueryRow(ctx, verifyAndConsumeToken, arg.TokenHash, arg.Purpose)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
