// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO
  users (username, email, name, google_id, is_active)
VALUES
  ($1, $2, $3, $4, TRUE)
RETURNING
  id, username, email, password_hash, name, role, google_id, is_active, created_at
`

type CreateOAuthUserParams struct {
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Name     pgtype.Text `json:"name"`
	GoogleID pgtype.Text `json:"google_id"`
}

func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOAuthUser,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.GoogleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (username, email, password_hash, is_active)
VALUES
  ($1, $2, $3, FALSE)
RETURNING
  id, username, email, password_hash, name, role, google_id, is_active, created_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE
  id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT
  users.id, users.username, users.email, users.password_hash, users.name, users.role, users.google_id, users.is_active, users.created_at
FROM
  users
ORDER BY
  id
LIMIT
  $1
OFFSET
  $2
`

type GetAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.GoogleID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id, username, email, password_hash, name, role, google_id, is_active, created_at
FROM
  users
WHERE
  email = $1
LIMIT
  1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT
  id, username, email, password_hash, name, role, google_id, is_active, created_at
FROM
  users
WHERE
  google_id = $1
LIMIT
  1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id, username, email, password_hash, name, role, google_id, is_active, created_at
FROM
  users
WHERE
  id = $1
LIMIT
  1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserGoogleID = `-- name: UpdateUserGoogleID :execrows
UPDATE users
SET
  google_id = $2
WHERE
  id = $1
  AND google_id IS NULL
`

type UpdateUserGoogleIDParams struct {
	ID       int32       `json:"id"`
	GoogleID pgtype.Text `json:"google_id"`
}

func (q *Queries) UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserGoogleID, arg.ID, arg.GoogleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserIsActiveReturning = `-- name: UpdateUserIsActiveReturning :one
UPDATE users
SET
  is_active = $2
WHERE
  id = $1
RETURNING
  users.id, users.username, users.email, users.password_hash, users.name, users.role, users.google_id, users.is_active, users.created_at
`

type UpdateUserIsActiveReturningParams struct {
	ID       int32 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) UpdateUserIsActiveReturning(ctx context.Context, arg UpdateUserIsActiveReturningParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserIsActiveReturning, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET
  password_hash = $2
WHERE
  id = $1
`

type UpdateUserPasswordParams struct {
	ID           int32       `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users
SET
  username = $2,
  email = $3
WHERE
  id = $1
`

type UpdateUserProfileParams struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.Username, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
