// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    user_id, name, amount, type, category, date, due_date, paid, paid_at, recurrent, frequency, receipt_url  
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, false, $8, false, $9, $10
)
RETURNING id, user_id, name, amount, type, category, date, due_date, paid, paid_at, recurrent, frequency, receipt_url
`

type CreatePaymentParams struct {
	UserID     int32             `json:"user_id"`
	Name       string            `json:"name"`
	Amount     pgtype.Numeric    `json:"amount"`
	Type       TransactionType   `json:"type"`
	Category   CategoryType      `json:"category"`
	Date       string            `json:"date"`
	DueDate    pgtype.Text       `json:"due_date"`
	PaidAt     pgtype.Text       `json:"paid_at"`
	Frequency  NullFrequencyType `json:"frequency"`
	ReceiptUrl pgtype.Text       `json:"receipt_url"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.Category,
		arg.Date,
		arg.DueDate,
		arg.PaidAt,
		arg.Frequency,
		arg.ReceiptUrl,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.Category,
		&i.Date,
		&i.DueDate,
		&i.Paid,
		&i.PaidAt,
		&i.Recurrent,
		&i.Frequency,
		&i.ReceiptUrl,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :execrows
DELETE FROM payments
WHERE id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletePayment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllPayments = `-- name: GetAllPayments :many
SELECT id, user_id, name, amount, type, category, date, due_date, paid, paid_at, recurrent, frequency, receipt_url FROM payments
`

func (q *Queries) GetAllPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getAllPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.Date,
			&i.DueDate,
			&i.Paid,
			&i.PaidAt,
			&i.Recurrent,
			&i.Frequency,
			&i.ReceiptUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPaymentsFromUser = `-- name: GetAllPaymentsFromUser :many
SELECT p.id, p.user_id, p.name, p.amount, p.type, p.category, p.date, p.due_date, p.paid, p.paid_at, p.recurrent, p.frequency, p.receipt_url FROM payments p
INNER JOIN users u ON p.user_id = u.id
WHERE u.email = $1
`

func (q *Queries) GetAllPaymentsFromUser(ctx context.Context, email string) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getAllPaymentsFromUser, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.Date,
			&i.DueDate,
			&i.Paid,
			&i.PaidAt,
			&i.Recurrent,
			&i.Frequency,
			&i.ReceiptUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, user_id, name, amount, type, category, date, due_date, paid, paid_at, recurrent, frequency, receipt_url FROM payments 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int32) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.Category,
		&i.Date,
		&i.DueDate,
		&i.Paid,
		&i.PaidAt,
		&i.Recurrent,
		&i.Frequency,
		&i.ReceiptUrl,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :execrows
UPDATE payments 
SET
	name = $2,
    amount = $3,
    type = $4,
    category = $5, 
    date = $6,
    due_date = $7,
    paid = $8,
    paid_at = $9,
    recurrent = $10,
    frequency = $11,
    receipt_url = $12
WHERE id = $1
`

type UpdatePaymentParams struct {
	ID         int32             `json:"id"`
	Name       string            `json:"name"`
	Amount     pgtype.Numeric    `json:"amount"`
	Type       TransactionType   `json:"type"`
	Category   CategoryType      `json:"category"`
	Date       string            `json:"date"`
	DueDate    pgtype.Text       `json:"due_date"`
	Paid       bool              `json:"paid"`
	PaidAt     pgtype.Text       `json:"paid_at"`
	Recurrent  bool              `json:"recurrent"`
	Frequency  NullFrequencyType `json:"frequency"`
	ReceiptUrl pgtype.Text       `json:"receipt_url"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePayment,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.Category,
		arg.Date,
		arg.DueDate,
		arg.Paid,
		arg.PaidAt,
		arg.Recurrent,
		arg.Frequency,
		arg.ReceiptUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
