// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePayment(ctx context.Context, id int32) (int64, error)
	DeleteUser(ctx context.Context, id int32) (int64, error)
	GetAllPayments(ctx context.Context) ([]Payment, error)
	GetAllPaymentsFromUser(ctx context.Context, email string) ([]Payment, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetPaymentByID(ctx context.Context, id int32) (Payment, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (int64, error)
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
