// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password, active, email_verification_hash, timeout
) VALUES (
    $1, $2, $3, false, $4, $5
)
RETURNING id, username, email, password, active, email_verification_hash, created_at, timeout
`

type CreateUserParams struct {
	Username              string          `json:"username"`
	Email                 string          `json:"email"`
	Password              string          `json:"password"`
	EmailVerificationHash pgtype.Text     `json:"email_verification_hash"`
	Timeout               pgtype.Interval `json:"timeout"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.EmailVerificationHash,
		arg.Timeout,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Active,
		&i.EmailVerificationHash,
		&i.CreatedAt,
		&i.Timeout,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users 
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, password, active, email_verification_hash, created_at, timeout FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Active,
			&i.EmailVerificationHash,
			&i.CreatedAt,
			&i.Timeout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, active, email_verification_hash, created_at, timeout FROM users 
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Active,
		&i.EmailVerificationHash,
		&i.CreatedAt,
		&i.Timeout,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, active, email_verification_hash, created_at, timeout FROM users 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Active,
		&i.EmailVerificationHash,
		&i.CreatedAt,
		&i.Timeout,
	)
	return i, err
}

const updateUserActive = `-- name: UpdateUserActive :execrows
UPDATE users 
SET
    active = $2
WHERE id = $1
`

type UpdateUserActiveParams struct {
	ID     int32 `json:"id"`
	Active bool  `json:"active"`
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserActive, arg.ID, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users 
SET
    password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int32  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users 
SET 
    username = $2,
    email = $3
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.Username, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
